import { StyleSheet } from 'react-native';
import { fonts, layout, radius, spacing } from '@/theme';

export const accountStyles = StyleSheet.create({
  profileCard: {
    borderRadius: radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    minHeight: 88,
    padding: spacing.lg,
  },
  profileIdentity: { alignItems: 'center', flexDirection: 'row', gap: spacing.md },
  avatar: { alignItems: 'center', borderRadius: 28, height: 56, justifyContent: 'center', width: 56 },
  avatarText: { fontFamily: fonts.displayExtraBold, fontSize: 22 },
  flex: { flex: 1 },
  profileName: { fontFamily: fonts.display, fontSize: 18, letterSpacing: -0.35 },
  profileEmail: { fontFamily: fonts.regular, fontSize: 13, lineHeight: 19, marginTop: 2 },
  message: { alignItems: 'center', borderRadius: radius.sm, flexDirection: 'row', gap: spacing.sm, padding: spacing.md },
  messageText: { flex: 1, fontFamily: fonts.medium, fontSize: 12.5, lineHeight: 18 },
  groupSection: { gap: spacing.sm },
  groupTitle: {
    fontFamily: fonts.bold,
    fontSize: 11,
    letterSpacing: 0.9,
    marginLeft: spacing.xs,
    textTransform: 'uppercase',
  },
  group: { borderRadius: radius.md, borderWidth: StyleSheet.hairlineWidth, overflow: 'hidden' },
  item: { borderBottomWidth: StyleSheet.hairlineWidth },
  itemHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 76,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  itemIcon: { alignItems: 'center', borderRadius: 12, height: 40, justifyContent: 'center', width: 40 },
  itemTitle: { fontFamily: fonts.semibold, fontSize: 14, lineHeight: 19 },
  itemDetail: { fontFamily: fonts.regular, fontSize: 11.5, lineHeight: 17, marginTop: 1 },
  itemStatus: { fontFamily: fonts.semibold, fontSize: 11, lineHeight: 16, marginTop: 4 },
  itemBody: { borderTopWidth: StyleSheet.hairlineWidth, gap: spacing.md, padding: spacing.lg },
  body: { fontFamily: fonts.regular, fontSize: 13, lineHeight: 20 },
  footnote: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 },
  progressSummary: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm },
  completedToggle: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
  actionStack: { gap: spacing.sm },
  fieldLabel: { fontFamily: fonts.bold, fontSize: 9.5, letterSpacing: 1, marginBottom: -4 },
  address: { fontFamily: fonts.medium, fontSize: 12, lineHeight: 18 },
  input: {
    borderRadius: radius.sm,
    borderWidth: 1,
    fontFamily: fonts.medium,
    fontSize: 14,
    minHeight: 50,
    paddingHorizontal: spacing.md,
  },
  signature: { minHeight: 88, paddingVertical: spacing.md, textAlignVertical: 'top' },
  challenge: { borderRadius: radius.sm, fontFamily: fonts.regular, fontSize: 11, lineHeight: 17, padding: spacing.md },
  subsection: { borderTopWidth: StyleSheet.hairlineWidth, gap: spacing.md, marginTop: spacing.xs, paddingTop: spacing.lg },
  subsectionHeading: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  smallIcon: { alignItems: 'center', borderRadius: 9, height: 32, justifyContent: 'center', width: 32 },
  progressTrack: { borderRadius: radius.pill, height: 7, overflow: 'hidden' },
  progressFill: { borderRadius: radius.pill, height: '100%' },
  checklist: { gap: spacing.sm },
  checkRow: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm, minHeight: 36, paddingVertical: spacing.xs },
  checkText: { flex: 1, fontFamily: fonts.medium, fontSize: 12.5, lineHeight: 18 },
  pendingDot: { borderRadius: 10, borderWidth: 1.5, height: 20, width: 20 },
  quizRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 48 },
  quizBox: { borderRadius: 6, borderWidth: 1.5, height: 21, width: 21 },
  quizText: { flex: 1, fontFamily: fonts.regular, fontSize: 12.5, lineHeight: 18 },
  preference: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, minHeight: 66 },
  preferenceName: { fontFamily: fonts.medium, fontSize: 13 },
  preferenceDetail: { fontFamily: fonts.regular, fontSize: 11, lineHeight: 16, marginTop: 2 },
  segmented: { borderRadius: layout.controlRadius, flexDirection: 'row', gap: spacing.xs, padding: spacing.xs },
  segmentWrap: { flex: 1 },
  segment: {
    alignItems: 'center',
    borderColor: 'transparent',
    borderRadius: layout.controlRadius,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.sm,
  },
  segmentText: { fontFamily: fonts.semibold, fontSize: 12 },
  dangerCopy: { fontFamily: fonts.medium, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  versionNote: { fontFamily: fonts.medium, fontSize: 10.5, lineHeight: 16, textAlign: 'center' },
});
