import { useState } from 'react';
import { Linking, Platform, StyleSheet, Text, View } from 'react-native';
import { ArrowCounterClockwise, CreditCard, LockKey, Wallet } from 'phosphor-react-native';
import { useAuth } from '@/auth/provider';
import { purchasePolyClawBot, restorePolyClawBot } from '@/billing/revenuecat';
import { ActionButton, Card, Header, money, Screen, StatusPill } from '@/components/ui-kit';
import { useConsumerDashboard } from '@/hooks/use-consumer-dashboard';
import { fonts, spacing, usePolyClawTheme } from '@/theme';

export default function ConsumerWallet() {
  const { theme } = usePolyClawTheme(); const { session, consumer } = useAuth(); const resource = useConsumerDashboard(60_000); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const billing = async (restore: boolean) => { if (!session) return; setBusy(true); setMessage(null); try { if (restore) await restorePolyClawBot(session.user.id); else await purchasePolyClawBot(session.user.id); setMessage(restore ? 'Purchases restored. Entitlement sync may take a moment.' : 'Subscription confirmed. Entitlement sync may take a moment.'); await resource.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Billing is unavailable'); } finally { setBusy(false); } };
  const directCheckout = async () => { setBusy(true); setMessage(null); try { const checkout = await consumer<{ url: string }>('createKoraCheckout'); await Linking.openURL(checkout.url); } catch (error) { setMessage(error instanceof Error ? error.message : 'Direct checkout is unavailable'); } finally { setBusy(false); } };
  return <Screen><Header eyebrow="PAPER FUNDS & ACCESS" title="Wallet" />
    <Card variant="raised"><View style={styles.row}><View style={[styles.icon, { backgroundColor: theme.accentSoft }]}><Wallet size={24} color={theme.accent} weight="fill" /></View><View style={styles.flex}><Text style={[styles.label, { color: theme.textMuted }]}>SIMULATED BALANCE</Text><Text style={[styles.balance, { color: theme.text }]}>{money(resource.data?.summary.equityUsdc ?? 1000)}</Text></View><StatusPill label="PAPER" tone="success" /></View><Text style={[styles.copy, { color: theme.textMuted }]}>This balance cannot be deposited, withdrawn, or converted to real money.</Text></Card>
    <Card><View style={styles.row}><CreditCard size={23} color={theme.accent} /><View style={styles.flex}><Text style={[styles.heading, { color: theme.text }]}>PolyClaw Bot · $9.99/month</Text><Text style={[styles.copy, { color: theme.textMuted }]}>7-day trial, then monthly. Store builds use Apple or Google billing; approved direct builds can use Kora.</Text></View></View><StatusPill label={resource.data?.entitlement?.status ?? 'NOT STARTED'} tone={resource.data?.entitlement?.active ? 'success' : 'warning'} />{!resource.data?.entitlement?.active ? <ActionButton label="Subscribe" icon={CreditCard as never} loading={busy} onPress={() => void billing(false)} /> : null}{Platform.OS === 'android' && process.env.EXPO_PUBLIC_POLYCLAW_KORA_ENABLED === 'true' ? <ActionButton label="Pay with Kora" icon={CreditCard as never} variant="secondary" loading={busy} onPress={() => void directCheckout()} /> : null}<ActionButton label="Restore purchases" icon={ArrowCounterClockwise as never} variant="secondary" loading={busy} onPress={() => void billing(true)} />{message ? <Text style={[styles.message, { color: theme.textMuted }]}>{message}</Text> : null}</Card>
    <Card><View style={styles.row}><LockKey size={23} color={theme.textMuted} /><View style={styles.flex}><Text style={[styles.heading, { color: theme.text }]}>Live wallet is not available</Text><Text style={[styles.copy, { color: theme.textMuted }]}>Polymarket account linking, funding, withdrawals, and live delegated trading stay locked until the separate custody, compliance, and store-policy gates are approved.</Text></View></View></Card>
  </Screen>;
}
const styles = StyleSheet.create({ row: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 }, icon: { alignItems: 'center', borderRadius: 15, height: 48, justifyContent: 'center', width: 48 }, flex: { flex: 1 }, label: { fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.3 }, balance: { fontFamily: fonts.displayExtraBold, fontSize: 30, marginTop: 3 }, heading: { fontFamily: fonts.display, fontSize: 15 }, copy: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, marginTop: 4 }, message: { fontFamily: fonts.medium, fontSize: 11.5, lineHeight: 17, marginTop: spacing.sm } });
